# Generated by Django 3.2.3 on 2021-06-02 12:25

from django.db import migrations, models
import handleApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=handleApi.models.generateUniqueCode, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('guestCanPause', models.BooleanField(default=False)),
                ('votesToSkip', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
